[BDHK-206] Implement whitelisting for addresses that can execute tx onchain
blndgs/bundler pull request #22
Opened 2024-06-28 14:32 UTC by adelowo

2024-07-02 06:41 UTC, singhhp1069 commented on srv/whitelist.go
> +}
```suggestion
func CheckSenderWhitelist(db *badger.DB, 
whitelistedAddresses []common.Address, 
logger logr.Logger) modules.BatchHandlerFunc {
	logger.Info("Setting up addresses in BadgerDB for whitelist checks")
	if len(whitelistedAddresses) > 0 {
		logger.Info("Bundler address whitelisting enabled", "number_of_whitelisted_addresses", len(whitelistedAddresses))
	}

	// Use a single transaction to store all addresses
	err := db.Update(func(txn *badger.Txn) error {
		for _, addr := range whitelistedAddresses {
			if err := txn.Set([]byte(getWhitelistKey(addr)), addr.Bytes()); err != nil {
				logger.Error(err, "Failed to store address in DB for whitelisting", "address", addr.Hex())
				return err
			}
			logger.Info("Address stored in DB whitelist", "address", addr.Hex())
		}
		return nil
	})

	if err != nil {
		logger.Error(err, "Failed to store multiple addresses in BadgerDB")
		return nil
	}

	return func(ctx *modules.BatchHandlerCtx) error {

		_, span := utils.GetTracer().
			Start(context.Background(), "WithAdressWhitelist")
		defer span.End()

		if len(whitelistedAddresses) == 0 {
			logger.Info("Address whitelisting not enabled. Skipping middleware.")
			return nil
		}

		for _, userop := range ctx.Batch {
			senderKey := getWhitelistKey(userop.Sender)
			err := db.View(func(txn *badger.Txn) error {
				_, err := txn.Get([]byte(senderKey))
				return err
			})
			if err != nil {
				logger.Error(err, "Sender not found in whitelist; cannot execute transaction", "address", userop.Sender.Hex())
				return err
			}
		}
		return nil
	}
}
```

2024-07-02 06:42 UTC, singhhp1069 requested changes
couple of suggestions:

1. Removed the panic on error and instead returned errors when they occurred during the DB operation.
2. Change the function to batch all whitelisted address insertions into a single BadgerDB transaction instead of separate transactions for each address.
3. Add godoc.
4. Add test cases.

2024-07-05 10:06 UTC, blewater requested changes
Nice touch with the database! A few comments.

2024-07-05 10:06 UTC, blewater commented on cmd/main.go
> +		whitelistHandler,
Why not first like an app firewall?

2024-07-05 10:06 UTC, blewater commented on srv/whitelist.go
> +	return fmt.Sprintf("bundler-whitelist-%s", addr.Hex())
`bundler-` is redundant, no other component uses this badger db instance.

2024-07-05 10:06 UTC, blewater commented on srv/whitelist_test.go
> +	}
you may use a memory badger instance which does not leave artifacts.
```Go
    db, err := badger.Open(badger.DefaultOptions("").WithInMemory(true))
```

2024-07-05 10:06 UTC, blewater commented on srv/whitelist.go
> +			}
Filter out any non-allowed rather than reject the batch.

2024-07-05 10:06 UTC, blewater commented on srv/whitelist_test.go
> +	}))
Add use case scenarios that check post-filtering batch counts:
1. Empty whitelist
2. Mixed allowed non-allowed white lists
3. All whitelisted addresses.

2024-07-09 15:30 UTC, singhhp1069 approved these changes

2024-07-09 15:58 UTC, blewater approved these changes
Nice work!

2024-07-09 15:58 UTC, blewater commented on srv/whitelist.go
> +				ctx.Batch = append(ctx.Batch[:idx], ctx.Batch[idx+1:]...)
👍

2024-07-09 16:00 UTC, merged